version: '3.8'

services:
  php-fpm:
    build:
      context: ./docker/etc/dev/php-fpm
      dockerfile: Dockerfile
      args:
        CURRENT_USER: '${CURRENT_USER}'
        CURRENT_GROUP: '${CURRENT_GROUP}'
        DIR_BASE: '${DIR_BASE}'
    container_name: workhubua_php-fpm
    volumes:
      - '.${DIR_APP}:${DIR_BASE}'
      - '.${PHP_DEV_CONF}:/usr/local/etc/php/conf.d/php.ini'
      - '.${PHP_CERTIFICATES}:/certificates'
    depends_on:
      - postgres
    networks:
      - workhubua

  nginx:
    image: nginx
    container_name: workhubua_nginx
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - '.${DIR_APP}:/var/www/html'
      - '.${NGINX_CONF}:/etc/nginx/conf.d/default.conf'
    depends_on:
      - php-fpm
    networks:
      - workhubua

  postgres:
    image: postgres
    container_name: workhubua_postgres
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - '5432:5432'
    volumes:
      - '.${DB_VOLUME}:/var/lib/postgresql/data'
    networks:
      - workhubua

  redis:
    image: redis
    container_name: workhubua_redis
    ports:
      - '6379:6379'
    volumes:
      - '.${REDIS_VOLUME}:/data'
    networks:
      - workhubua

networks:
  workhubua:
    name: workhubua