version: '3.8'

services:
  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: workhubua_php
    volumes:
      - ./app:/var/www/html
      - ./docker/php/php.ini:/usr/local/etc/php/conf.d/custom.ini
    environment:
      - APP_ENV=dev
      - DATABASE_URL=postgresql://workhubua:password@postgres:5432/workhubua
      - REDIS_URL=redis://redis:6379
    depends_on:
      - postgres
      - redis
    networks:
      - workhubua_network

  nginx:
    image: nginx:1.25-alpine
    container_name: workhubua_nginx
    ports:
      - "8080:80"
    volumes:
      - ./app:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    networks:
      - workhubua_network

  postgres:
    image: postgres:16-alpine
    container_name: workhubua_postgres
    environment:
      POSTGRES_DB: workhubua
      POSTGRES_USER: workhubua
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - workhubua_network

  redis:
    image: redis:7-alpine
    container_name: workhubua_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - workhubua_network

volumes:
  postgres_data:
  redis_data:

networks:
  workhubua_network:
    driver: bridge